# Generated by Django 3.1.3 on 2024-04-14 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcode', models.CharField(max_length=10, unique=True)),
                ('wname', models.TextField(max_length=20)),
                ('wplace', models.TextField(max_length=20)),
                ('port', models.TextField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('upload_imgfile', models.ImageField(blank=True, max_length=500, null=True, upload_to='question/%Y%m%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_result', models.TextField()),
                ('wname', models.TextField(max_length=20)),
                ('wplace', models.TextField(max_length=20)),
                ('port', models.TextField(max_length=20)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('predicted_imgfile', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_answer', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.question')),
            ],
        ),
    ]
